# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secret',
            name='likes',
        ),
        migrations.AddField(
            model_name='secret',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
